# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_extension.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'file_extension.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ile_extension.proto\"$\n\x0f\x46ilePathRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"*\n\x15\x46ileExtensionResponse\x12\x11\n\textension\x18\x01 \x01(\t2M\n\rFileExtension\x12<\n\x10GetFileExtension\x12\x10.FilePathRequest\x1a\x16.FileExtensionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_extension_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEPATHREQUEST']._serialized_start=24
  _globals['_FILEPATHREQUEST']._serialized_end=60
  _globals['_FILEEXTENSIONRESPONSE']._serialized_start=62
  _globals['_FILEEXTENSIONRESPONSE']._serialized_end=104
  _globals['_FILEEXTENSION']._serialized_start=106
  _globals['_FILEEXTENSION']._serialized_end=183
# @@protoc_insertion_point(module_scope)
